#!/usr/bin/env python3
"""Build the "what's below" lookup (src/region_data.c).

The world is divided into a 1 degree grid (360x180 cells). Each cell holds
the index of the country or ocean at its centre; rows are run-length encoded
(about 10 KB in all). The grid and names are kept as gfx/regions.png (an
index image) and gfx/regions.txt (one name per index), so rebuilding the C
data needs only Pillow.

Sources are Natural Earth 1:110m admin-0 countries and marine areas (public
domain), GeoJSON from https://github.com/nvkelso/natural-earth-vector.
Countries are drawn over seas; any ocean cell that no marine polygon covers
is named by a simple longitude/latitude rule.

Usage:
  mkregions.py gfx/regions.png gfx/regions.txt src/region_data.c
  mkregions.py --countries ne_110m_admin_0_countries.geojson \\
               --marine ne_110m_geography_marine_polys.geojson \\
               gfx/regions.png gfx/regions.txt src/region_data.c
"""

import argparse
import json

from PIL import Image, ImageDraw

W, H = 360, 180
SUPER = 4                       # render at 4x, sample cell centres
NAME_MAX = 22                   # "Over: " + name fits the status field


def tidy(name):
    """SOUTHERN OCEAN -> Southern Ocean; keep Natural Earth's short forms."""
    if name.isupper():
        name = " ".join(w.capitalize() for w in name.split())
    name = name.replace("United States of America", "United States")
    return name[:NAME_MAX]


def rings(geometry):
    if geometry["type"] == "Polygon":
        polys = [geometry["coordinates"]]
    else:
        polys = geometry["coordinates"]
    for poly in polys:
        yield poly[0]           # outer ring only; holes are rare at 1:110m


def draw_features(draw, features, name_of, names):
    for f in features:
        name = tidy(name_of(f["properties"]))
        if name not in names:
            names.append(name)
        idx = names.index(name)
        for ring in rings(f["geometry"]):
            pts = [((lon + 180) * SUPER, (90 - lat) * SUPER) for lon, lat in ring]
            if len(pts) > 2:
                draw.polygon(pts, fill=idx)


def fallback_ocean(lat, lon):
    if lat > 66:
        return "Arctic Ocean"
    if lat < -60:
        return "Southern Ocean"
    if 20 < lon <= 147 and lat < 25:
        return "Indian Ocean"
    atlantic = -70 <= lon <= 20 if lat < 10 else -100 <= lon <= 20
    hemi = "North" if lat >= 0 else "South"
    return f"{hemi} {'Atlantic' if atlantic else 'Pacific'} Ocean"


def rasterise(countries_path, marine_path, png, txt):
    names = ["?"]               # index 0: nothing drawn yet
    big = Image.new("L", (W * SUPER, H * SUPER), 0)
    draw = ImageDraw.Draw(big)
    with open(marine_path) as f:
        draw_features(draw, json.load(f)["features"], lambda p: p["name"], names)
    with open(countries_path) as f:
        draw_features(draw, json.load(f)["features"], lambda p: p["NAME"], names)

    grid = Image.new("L", (W, H))
    for y in range(H):
        for x in range(W):
            v = big.getpixel((x * SUPER + SUPER // 2, y * SUPER + SUPER // 2))
            if v == 0:
                name = fallback_ocean(89.5 - y, x - 179.5)
                if name not in names:
                    names.append(name)
                v = names.index(name)
            grid.putpixel((x, y), v)
    assert len(names) <= 256, len(names)
    grid.save(png)
    with open(txt, "w", encoding="latin-1") as f:
        f.write("\n".join(names) + "\n")


def build(png, txt, out_c):
    grid = Image.open(png)
    with open(txt, encoding="latin-1") as f:
        names = [line.rstrip("\n") for line in f]

    runs = bytearray()
    offsets = []
    for y in range(H):
        offsets.append(len(runs))
        row = [grid.getpixel((x, y)) for x in range(W)]
        x = 0
        while x < W:
            n = 1
            while x + n < W and row[x + n] == row[x] and n < 255:
                n += 1
            runs += bytes((n, row[x]))
            x += n

    def cstr(s):
        out = ""
        for ch in s.encode("latin-1"):
            out += chr(ch) if 32 <= ch < 127 and ch not in (34, 92) else "\\%03o" % ch
        return '"' + out + '"'

    with open(out_c, "w") as f:
        f.write("/* GENERATED by tools/mkregions.py from gfx/regions.png and\n"
                " * gfx/regions.txt - do not edit. Natural Earth 1:110m countries and\n"
                " * marine areas (public domain), 1 degree cells, row RLE. */\n\n")
        f.write('#include "region_data.h"\n\n')
        f.write("const char *const region_names[%d] =\n{\n" % len(names))
        for n in names:
            f.write("    %s,\n" % cstr(n))
        f.write("};\n\n")
        f.write("const unsigned short region_rows[REGION_H] =\n{\n")
        for i in range(0, H, 12):
            f.write("    " + ",".join(str(o) for o in offsets[i:i + 12]) + ",\n")
        f.write("};\n\n")
        f.write("/* (count, name index) pairs */\n")
        f.write("const unsigned char region_runs[%d] =\n{\n" % len(runs))
        for i in range(0, len(runs), 24):
            f.write("    " + ",".join(str(b) for b in runs[i:i + 24]) + ",\n")
        f.write("};\n")
    print(f"{out_c}: {len(names)} names, {len(runs)} bytes of runs")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--countries", help="Natural Earth admin-0 countries GeoJSON")
    ap.add_argument("--marine", help="Natural Earth marine polygons GeoJSON")
    ap.add_argument("png")
    ap.add_argument("txt")
    ap.add_argument("out_c")
    a = ap.parse_args()
    if a.countries or a.marine:
        if not (a.countries and a.marine):
            ap.error("--countries and --marine go together")
        rasterise(a.countries, a.marine, a.png, a.txt)
    build(a.png, a.txt, a.out_c)


if __name__ == "__main__":
    main()
