#!/usr/bin/env python3
"""Generate coco/src/map_coco3.h (the CoCo 3 640x192 world map).

Source : NASA Blue Marble equirectangular (Wikimedia), downscaled to 640x160
         and reduced to a 2-colour ocean/land bitmap, RLE compressed.
Output : ../src/map_coco3.h  (decompresses to 30720 bytes = 160 bytes/row x 192,
         rows 0-159 = map, rows 160-191 = ocean; the CoCo 3 OSD panel covers them).

Requires: curl, ffmpeg, python3. No third-party python modules.
Usage   : python3 genmap.py
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "map_coco3.h")
CACHE = os.path.join(HERE, "bluemarble.jpg")
PPM = os.path.join(HERE, "bluemarble.ppm")
SRC_URL = ("https://upload.wikimedia.org/wikipedia/commons/8/83/"
           "Equirectangular_projection_SW.jpg")

OW, OH = 640, 160          # map area; rows 160-191 are filled with ocean


def run(cmd):
    subprocess.run(cmd, check=True)


def read_ppm(path):
    data = open(path, "rb").read()
    assert data[:2] == b"P6", "expected binary PPM"
    i, fields = 2, []
    while len(fields) < 3:
        while data[i] in b" \t\n\r":
            i += 1
        s = i
        while data[i] not in b" \t\n\r":
            i += 1
        fields.append(int(data[s:i]))
    i += 1
    w, h, _ = fields
    return w, h, data[i:]


def main():
    if not os.path.exists(CACHE):
        run(["curl", "-sL", "--max-time", "60", "-o", CACHE, SRC_URL])
    run(["ffmpeg", "-y", "-loglevel", "error", "-i", CACHE,
         "-pix_fmt", "rgb24", PPM])

    w, h, px = read_ppm(PPM)

    # ocean = clearly blue water; everything else (land/ice) = land
    mask = bytearray(w * h)
    for p in range(w * h):
        b3 = p * 3
        r, g, b = px[b3], px[b3 + 1], px[b3 + 2]
        mask[p] = 0 if (b > r + 30 and b > 100) else 1

    # area-average to coverage, threshold at 50%
    grid = [[0] * OW for _ in range(OH)]
    for oy in range(OH):
        y0, y1 = oy * h // OH, max(oy * h // OH + 1, (oy + 1) * h // OH)
        for ox in range(OW):
            x0, x1 = ox * w // OW, max(ox * w // OW + 1, (ox + 1) * w // OW)
            s = c = 0
            for yy in range(y0, y1):
                base = yy * w
                for xx in range(x0, x1):
                    s += mask[base + xx]
                    c += 1
            grid[oy][ox] = 1 if (s / c) >= 0.5 else 0

    for oy in range(OH):                       # left-edge artifact
        grid[oy][0] = grid[oy][1]
    y = 0                                      # solid Arctic ice cap -> ocean
    while y < 8 and sum(grid[y]) > OW * 0.85:
        grid[y] = [0] * OW
        y += 1

    rows = grid + [[0] * OW for _ in range(192 - OH)]
    packed = bytearray()
    for row in rows:
        for bx in range(0, OW, 4):
            packed.append((row[bx] << 6) | (row[bx + 1] << 4) |
                          (row[bx + 2] << 2) | row[bx + 3])

    rle = bytearray()
    i = 0
    while i < len(packed):
        v, run_len = packed[i], 1
        while i + run_len < len(packed) and packed[i + run_len] == v and run_len < 255:
            run_len += 1
        rle += bytes((run_len, v))
        i += run_len

    with open(OUT, "w") as h_out:
        h_out.write("/* Generated by coco/support/genmap.py from NASA Blue Marble.\n")
        h_out.write(" * 2bpp 0=ocean 1=land, byte-RLE. Decompresses to 30720 bytes\n")
        h_out.write(" * = 160 bytes/row x 192 rows (rows 160-191 ocean). */\n\n")
        h_out.write("#ifndef MAP_COCO3_H\n#define MAP_COCO3_H\n\n")
        h_out.write("#define MAP_COCO3_RLE_LEN %d\n\n" % len(rle))
        h_out.write("static const unsigned char map_coco3_rle[%d] = {\n" % len(rle))
        for j in range(0, len(rle), 16):
            h_out.write("    " + ",".join("0x%02X" % b for b in rle[j:j + 16]) + ",\n")
        h_out.write("};\n\n#endif\n")

    os.remove(PPM)
    print("wrote %s (RLE %d bytes)" % (OUT, len(rle)))


if __name__ == "__main__":
    sys.exit(main())
